// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.studio6.app.common.proto;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WorkItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string creation_date = 2;
    /**
     * <code>required string creation_date = 2;</code>
     */
    boolean hasCreationDate();
    /**
     * <code>required string creation_date = 2;</code>
     */
    java.lang.String getCreationDate();
    /**
     * <code>required string creation_date = 2;</code>
     */
    com.google.protobuf.ByteString
        getCreationDateBytes();

    // required int64 max_process_ms = 3;
    /**
     * <code>required int64 max_process_ms = 3;</code>
     */
    boolean hasMaxProcessMs();
    /**
     * <code>required int64 max_process_ms = 3;</code>
     */
    long getMaxProcessMs();

    // required int64 max_attempts = 4;
    /**
     * <code>required int64 max_attempts = 4;</code>
     */
    boolean hasMaxAttempts();
    /**
     * <code>required int64 max_attempts = 4;</code>
     */
    long getMaxAttempts();

    // required int64 wait_between_attempts_ms = 5;
    /**
     * <code>required int64 wait_between_attempts_ms = 5;</code>
     */
    boolean hasWaitBetweenAttemptsMs();
    /**
     * <code>required int64 wait_between_attempts_ms = 5;</code>
     */
    long getWaitBetweenAttemptsMs();

    // required bytes item = 6;
    /**
     * <code>required bytes item = 6;</code>
     */
    boolean hasItem();
    /**
     * <code>required bytes item = 6;</code>
     */
    com.google.protobuf.ByteString getItem();

    // optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;
    /**
     * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
     */
    boolean hasInProgressAttempt();
    /**
     * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
     */
    com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt getInProgressAttempt();
    /**
     * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
     */
    com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder getInProgressAttemptOrBuilder();

    // repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    java.util.List<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt> 
        getAttemptList();
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt getAttempt(int index);
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    int getAttemptCount();
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    java.util.List<? extends com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder> 
        getAttemptOrBuilderList();
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder getAttemptOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.studio6.app.common.proto.WorkItem}
   */
  public static final class WorkItem extends
      com.google.protobuf.GeneratedMessage
      implements WorkItemOrBuilder {
    // Use WorkItem.newBuilder() to construct.
    private WorkItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorkItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorkItem defaultInstance;
    public static WorkItem getDefaultInstance() {
      return defaultInstance;
    }

    public WorkItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorkItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              creationDate_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              maxProcessMs_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              maxAttempts_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              waitBetweenAttemptsMs_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              item_ = input.readBytes();
              break;
            }
            case 58: {
              com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = inProgressAttempt_.toBuilder();
              }
              inProgressAttempt_ = input.readMessage(com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(inProgressAttempt_);
                inProgressAttempt_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                attempt_ = new java.util.ArrayList<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt>();
                mutable_bitField0_ |= 0x00000080;
              }
              attempt_.add(input.readMessage(com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          attempt_ = java.util.Collections.unmodifiableList(attempt_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.studio6.app.common.proto.CommonProtos.WorkItem.class, com.studio6.app.common.proto.CommonProtos.WorkItem.Builder.class);
    }

    public static com.google.protobuf.Parser<WorkItem> PARSER =
        new com.google.protobuf.AbstractParser<WorkItem>() {
      public WorkItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorkItem> getParserForType() {
      return PARSER;
    }

    public interface AttemptOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string creation_date = 1;
      /**
       * <code>required string creation_date = 1;</code>
       */
      boolean hasCreationDate();
      /**
       * <code>required string creation_date = 1;</code>
       */
      java.lang.String getCreationDate();
      /**
       * <code>required string creation_date = 1;</code>
       */
      com.google.protobuf.ByteString
          getCreationDateBytes();

      // optional string message = 2;
      /**
       * <code>optional string message = 2;</code>
       */
      boolean hasMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      java.lang.String getMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      com.google.protobuf.ByteString
          getMessageBytes();
    }
    /**
     * Protobuf type {@code com.studio6.app.common.proto.WorkItem.Attempt}
     */
    public static final class Attempt extends
        com.google.protobuf.GeneratedMessage
        implements AttemptOrBuilder {
      // Use Attempt.newBuilder() to construct.
      private Attempt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Attempt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Attempt defaultInstance;
      public static Attempt getDefaultInstance() {
        return defaultInstance;
      }

      public Attempt getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Attempt(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                creationDate_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                message_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_Attempt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_Attempt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.class, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder.class);
      }

      public static com.google.protobuf.Parser<Attempt> PARSER =
          new com.google.protobuf.AbstractParser<Attempt>() {
        public Attempt parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Attempt(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Attempt> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string creation_date = 1;
      public static final int CREATION_DATE_FIELD_NUMBER = 1;
      private java.lang.Object creationDate_;
      /**
       * <code>required string creation_date = 1;</code>
       */
      public boolean hasCreationDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string creation_date = 1;</code>
       */
      public java.lang.String getCreationDate() {
        java.lang.Object ref = creationDate_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            creationDate_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string creation_date = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCreationDateBytes() {
        java.lang.Object ref = creationDate_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creationDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string message = 2;
      public static final int MESSAGE_FIELD_NUMBER = 2;
      private java.lang.Object message_;
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        creationDate_ = "";
        message_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasCreationDate()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getCreationDateBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getMessageBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getCreationDateBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getMessageBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.studio6.app.common.proto.WorkItem.Attempt}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_Attempt_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_Attempt_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.class, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder.class);
        }

        // Construct using com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          creationDate_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          message_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_Attempt_descriptor;
        }

        public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt getDefaultInstanceForType() {
          return com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance();
        }

        public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt build() {
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt buildPartial() {
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt result = new com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.creationDate_ = creationDate_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.message_ = message_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt) {
            return mergeFrom((com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt other) {
          if (other == com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance()) return this;
          if (other.hasCreationDate()) {
            bitField0_ |= 0x00000001;
            creationDate_ = other.creationDate_;
            onChanged();
          }
          if (other.hasMessage()) {
            bitField0_ |= 0x00000002;
            message_ = other.message_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCreationDate()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string creation_date = 1;
        private java.lang.Object creationDate_ = "";
        /**
         * <code>required string creation_date = 1;</code>
         */
        public boolean hasCreationDate() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string creation_date = 1;</code>
         */
        public java.lang.String getCreationDate() {
          java.lang.Object ref = creationDate_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            creationDate_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string creation_date = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCreationDateBytes() {
          java.lang.Object ref = creationDate_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            creationDate_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string creation_date = 1;</code>
         */
        public Builder setCreationDate(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          creationDate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string creation_date = 1;</code>
         */
        public Builder clearCreationDate() {
          bitField0_ = (bitField0_ & ~0x00000001);
          creationDate_ = getDefaultInstance().getCreationDate();
          onChanged();
          return this;
        }
        /**
         * <code>required string creation_date = 1;</code>
         */
        public Builder setCreationDateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          creationDate_ = value;
          onChanged();
          return this;
        }

        // optional string message = 2;
        private java.lang.Object message_ = "";
        /**
         * <code>optional string message = 2;</code>
         */
        public boolean hasMessage() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public java.lang.String getMessage() {
          java.lang.Object ref = message_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            message_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMessageBytes() {
          java.lang.Object ref = message_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            message_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessage(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder clearMessage() {
          bitField0_ = (bitField0_ & ~0x00000002);
          message_ = getDefaultInstance().getMessage();
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.studio6.app.common.proto.WorkItem.Attempt)
      }

      static {
        defaultInstance = new Attempt(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.studio6.app.common.proto.WorkItem.Attempt)
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string creation_date = 2;
    public static final int CREATION_DATE_FIELD_NUMBER = 2;
    private java.lang.Object creationDate_;
    /**
     * <code>required string creation_date = 2;</code>
     */
    public boolean hasCreationDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string creation_date = 2;</code>
     */
    public java.lang.String getCreationDate() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          creationDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string creation_date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreationDateBytes() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 max_process_ms = 3;
    public static final int MAX_PROCESS_MS_FIELD_NUMBER = 3;
    private long maxProcessMs_;
    /**
     * <code>required int64 max_process_ms = 3;</code>
     */
    public boolean hasMaxProcessMs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 max_process_ms = 3;</code>
     */
    public long getMaxProcessMs() {
      return maxProcessMs_;
    }

    // required int64 max_attempts = 4;
    public static final int MAX_ATTEMPTS_FIELD_NUMBER = 4;
    private long maxAttempts_;
    /**
     * <code>required int64 max_attempts = 4;</code>
     */
    public boolean hasMaxAttempts() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 max_attempts = 4;</code>
     */
    public long getMaxAttempts() {
      return maxAttempts_;
    }

    // required int64 wait_between_attempts_ms = 5;
    public static final int WAIT_BETWEEN_ATTEMPTS_MS_FIELD_NUMBER = 5;
    private long waitBetweenAttemptsMs_;
    /**
     * <code>required int64 wait_between_attempts_ms = 5;</code>
     */
    public boolean hasWaitBetweenAttemptsMs() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 wait_between_attempts_ms = 5;</code>
     */
    public long getWaitBetweenAttemptsMs() {
      return waitBetweenAttemptsMs_;
    }

    // required bytes item = 6;
    public static final int ITEM_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString item_;
    /**
     * <code>required bytes item = 6;</code>
     */
    public boolean hasItem() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes item = 6;</code>
     */
    public com.google.protobuf.ByteString getItem() {
      return item_;
    }

    // optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;
    public static final int IN_PROGRESS_ATTEMPT_FIELD_NUMBER = 7;
    private com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt inProgressAttempt_;
    /**
     * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
     */
    public boolean hasInProgressAttempt() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
     */
    public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt getInProgressAttempt() {
      return inProgressAttempt_;
    }
    /**
     * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
     */
    public com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder getInProgressAttemptOrBuilder() {
      return inProgressAttempt_;
    }

    // repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;
    public static final int ATTEMPT_FIELD_NUMBER = 8;
    private java.util.List<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt> attempt_;
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    public java.util.List<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt> getAttemptList() {
      return attempt_;
    }
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    public java.util.List<? extends com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder> 
        getAttemptOrBuilderList() {
      return attempt_;
    }
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    public int getAttemptCount() {
      return attempt_.size();
    }
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt getAttempt(int index) {
      return attempt_.get(index);
    }
    /**
     * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
     */
    public com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder getAttemptOrBuilder(
        int index) {
      return attempt_.get(index);
    }

    private void initFields() {
      id_ = "";
      creationDate_ = "";
      maxProcessMs_ = 0L;
      maxAttempts_ = 0L;
      waitBetweenAttemptsMs_ = 0L;
      item_ = com.google.protobuf.ByteString.EMPTY;
      inProgressAttempt_ = com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance();
      attempt_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreationDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxProcessMs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxAttempts()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWaitBetweenAttemptsMs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasInProgressAttempt()) {
        if (!getInProgressAttempt().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getAttemptCount(); i++) {
        if (!getAttempt(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCreationDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, maxProcessMs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, maxAttempts_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, waitBetweenAttemptsMs_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, item_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, inProgressAttempt_);
      }
      for (int i = 0; i < attempt_.size(); i++) {
        output.writeMessage(8, attempt_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCreationDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, maxProcessMs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, maxAttempts_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, waitBetweenAttemptsMs_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, item_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, inProgressAttempt_);
      }
      for (int i = 0; i < attempt_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, attempt_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.studio6.app.common.proto.CommonProtos.WorkItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.studio6.app.common.proto.CommonProtos.WorkItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.studio6.app.common.proto.WorkItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.studio6.app.common.proto.CommonProtos.WorkItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.studio6.app.common.proto.CommonProtos.WorkItem.class, com.studio6.app.common.proto.CommonProtos.WorkItem.Builder.class);
      }

      // Construct using com.studio6.app.common.proto.CommonProtos.WorkItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInProgressAttemptFieldBuilder();
          getAttemptFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        creationDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        maxProcessMs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxAttempts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        waitBetweenAttemptsMs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        item_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (inProgressAttemptBuilder_ == null) {
          inProgressAttempt_ = com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance();
        } else {
          inProgressAttemptBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (attemptBuilder_ == null) {
          attempt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          attemptBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.studio6.app.common.proto.CommonProtos.internal_static_com_studio6_app_common_proto_WorkItem_descriptor;
      }

      public com.studio6.app.common.proto.CommonProtos.WorkItem getDefaultInstanceForType() {
        return com.studio6.app.common.proto.CommonProtos.WorkItem.getDefaultInstance();
      }

      public com.studio6.app.common.proto.CommonProtos.WorkItem build() {
        com.studio6.app.common.proto.CommonProtos.WorkItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.studio6.app.common.proto.CommonProtos.WorkItem buildPartial() {
        com.studio6.app.common.proto.CommonProtos.WorkItem result = new com.studio6.app.common.proto.CommonProtos.WorkItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.creationDate_ = creationDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxProcessMs_ = maxProcessMs_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxAttempts_ = maxAttempts_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.waitBetweenAttemptsMs_ = waitBetweenAttemptsMs_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.item_ = item_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (inProgressAttemptBuilder_ == null) {
          result.inProgressAttempt_ = inProgressAttempt_;
        } else {
          result.inProgressAttempt_ = inProgressAttemptBuilder_.build();
        }
        if (attemptBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            attempt_ = java.util.Collections.unmodifiableList(attempt_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.attempt_ = attempt_;
        } else {
          result.attempt_ = attemptBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.studio6.app.common.proto.CommonProtos.WorkItem) {
          return mergeFrom((com.studio6.app.common.proto.CommonProtos.WorkItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.studio6.app.common.proto.CommonProtos.WorkItem other) {
        if (other == com.studio6.app.common.proto.CommonProtos.WorkItem.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCreationDate()) {
          bitField0_ |= 0x00000002;
          creationDate_ = other.creationDate_;
          onChanged();
        }
        if (other.hasMaxProcessMs()) {
          setMaxProcessMs(other.getMaxProcessMs());
        }
        if (other.hasMaxAttempts()) {
          setMaxAttempts(other.getMaxAttempts());
        }
        if (other.hasWaitBetweenAttemptsMs()) {
          setWaitBetweenAttemptsMs(other.getWaitBetweenAttemptsMs());
        }
        if (other.hasItem()) {
          setItem(other.getItem());
        }
        if (other.hasInProgressAttempt()) {
          mergeInProgressAttempt(other.getInProgressAttempt());
        }
        if (attemptBuilder_ == null) {
          if (!other.attempt_.isEmpty()) {
            if (attempt_.isEmpty()) {
              attempt_ = other.attempt_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureAttemptIsMutable();
              attempt_.addAll(other.attempt_);
            }
            onChanged();
          }
        } else {
          if (!other.attempt_.isEmpty()) {
            if (attemptBuilder_.isEmpty()) {
              attemptBuilder_.dispose();
              attemptBuilder_ = null;
              attempt_ = other.attempt_;
              bitField0_ = (bitField0_ & ~0x00000080);
              attemptBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttemptFieldBuilder() : null;
            } else {
              attemptBuilder_.addAllMessages(other.attempt_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCreationDate()) {
          
          return false;
        }
        if (!hasMaxProcessMs()) {
          
          return false;
        }
        if (!hasMaxAttempts()) {
          
          return false;
        }
        if (!hasWaitBetweenAttemptsMs()) {
          
          return false;
        }
        if (!hasItem()) {
          
          return false;
        }
        if (hasInProgressAttempt()) {
          if (!getInProgressAttempt().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getAttemptCount(); i++) {
          if (!getAttempt(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.studio6.app.common.proto.CommonProtos.WorkItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.studio6.app.common.proto.CommonProtos.WorkItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string creation_date = 2;
      private java.lang.Object creationDate_ = "";
      /**
       * <code>required string creation_date = 2;</code>
       */
      public boolean hasCreationDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string creation_date = 2;</code>
       */
      public java.lang.String getCreationDate() {
        java.lang.Object ref = creationDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          creationDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string creation_date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCreationDateBytes() {
        java.lang.Object ref = creationDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creationDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string creation_date = 2;</code>
       */
      public Builder setCreationDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        creationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string creation_date = 2;</code>
       */
      public Builder clearCreationDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        creationDate_ = getDefaultInstance().getCreationDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string creation_date = 2;</code>
       */
      public Builder setCreationDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        creationDate_ = value;
        onChanged();
        return this;
      }

      // required int64 max_process_ms = 3;
      private long maxProcessMs_ ;
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      public boolean hasMaxProcessMs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      public long getMaxProcessMs() {
        return maxProcessMs_;
      }
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      public Builder setMaxProcessMs(long value) {
        bitField0_ |= 0x00000004;
        maxProcessMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      public Builder clearMaxProcessMs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxProcessMs_ = 0L;
        onChanged();
        return this;
      }

      // required int64 max_attempts = 4;
      private long maxAttempts_ ;
      /**
       * <code>required int64 max_attempts = 4;</code>
       */
      public boolean hasMaxAttempts() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 max_attempts = 4;</code>
       */
      public long getMaxAttempts() {
        return maxAttempts_;
      }
      /**
       * <code>required int64 max_attempts = 4;</code>
       */
      public Builder setMaxAttempts(long value) {
        bitField0_ |= 0x00000008;
        maxAttempts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 max_attempts = 4;</code>
       */
      public Builder clearMaxAttempts() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxAttempts_ = 0L;
        onChanged();
        return this;
      }

      // required int64 wait_between_attempts_ms = 5;
      private long waitBetweenAttemptsMs_ ;
      /**
       * <code>required int64 wait_between_attempts_ms = 5;</code>
       */
      public boolean hasWaitBetweenAttemptsMs() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 wait_between_attempts_ms = 5;</code>
       */
      public long getWaitBetweenAttemptsMs() {
        return waitBetweenAttemptsMs_;
      }
      /**
       * <code>required int64 wait_between_attempts_ms = 5;</code>
       */
      public Builder setWaitBetweenAttemptsMs(long value) {
        bitField0_ |= 0x00000010;
        waitBetweenAttemptsMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 wait_between_attempts_ms = 5;</code>
       */
      public Builder clearWaitBetweenAttemptsMs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        waitBetweenAttemptsMs_ = 0L;
        onChanged();
        return this;
      }

      // required bytes item = 6;
      private com.google.protobuf.ByteString item_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes item = 6;</code>
       */
      public boolean hasItem() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes item = 6;</code>
       */
      public com.google.protobuf.ByteString getItem() {
        return item_;
      }
      /**
       * <code>required bytes item = 6;</code>
       */
      public Builder setItem(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        item_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes item = 6;</code>
       */
      public Builder clearItem() {
        bitField0_ = (bitField0_ & ~0x00000020);
        item_ = getDefaultInstance().getItem();
        onChanged();
        return this;
      }

      // optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;
      private com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt inProgressAttempt_ = com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder, com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder> inProgressAttemptBuilder_;
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public boolean hasInProgressAttempt() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt getInProgressAttempt() {
        if (inProgressAttemptBuilder_ == null) {
          return inProgressAttempt_;
        } else {
          return inProgressAttemptBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public Builder setInProgressAttempt(com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt value) {
        if (inProgressAttemptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inProgressAttempt_ = value;
          onChanged();
        } else {
          inProgressAttemptBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public Builder setInProgressAttempt(
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder builderForValue) {
        if (inProgressAttemptBuilder_ == null) {
          inProgressAttempt_ = builderForValue.build();
          onChanged();
        } else {
          inProgressAttemptBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public Builder mergeInProgressAttempt(com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt value) {
        if (inProgressAttemptBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              inProgressAttempt_ != com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance()) {
            inProgressAttempt_ =
              com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.newBuilder(inProgressAttempt_).mergeFrom(value).buildPartial();
          } else {
            inProgressAttempt_ = value;
          }
          onChanged();
        } else {
          inProgressAttemptBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public Builder clearInProgressAttempt() {
        if (inProgressAttemptBuilder_ == null) {
          inProgressAttempt_ = com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance();
          onChanged();
        } else {
          inProgressAttemptBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder getInProgressAttemptBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getInProgressAttemptFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder getInProgressAttemptOrBuilder() {
        if (inProgressAttemptBuilder_ != null) {
          return inProgressAttemptBuilder_.getMessageOrBuilder();
        } else {
          return inProgressAttempt_;
        }
      }
      /**
       * <code>optional .com.studio6.app.common.proto.WorkItem.Attempt in_progress_attempt = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder, com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder> 
          getInProgressAttemptFieldBuilder() {
        if (inProgressAttemptBuilder_ == null) {
          inProgressAttemptBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder, com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder>(
                  inProgressAttempt_,
                  getParentForChildren(),
                  isClean());
          inProgressAttempt_ = null;
        }
        return inProgressAttemptBuilder_;
      }

      // repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;
      private java.util.List<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt> attempt_ =
        java.util.Collections.emptyList();
      private void ensureAttemptIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          attempt_ = new java.util.ArrayList<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt>(attempt_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder, com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder> attemptBuilder_;

      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public java.util.List<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt> getAttemptList() {
        if (attemptBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attempt_);
        } else {
          return attemptBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public int getAttemptCount() {
        if (attemptBuilder_ == null) {
          return attempt_.size();
        } else {
          return attemptBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt getAttempt(int index) {
        if (attemptBuilder_ == null) {
          return attempt_.get(index);
        } else {
          return attemptBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder setAttempt(
          int index, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt value) {
        if (attemptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttemptIsMutable();
          attempt_.set(index, value);
          onChanged();
        } else {
          attemptBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder setAttempt(
          int index, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder builderForValue) {
        if (attemptBuilder_ == null) {
          ensureAttemptIsMutable();
          attempt_.set(index, builderForValue.build());
          onChanged();
        } else {
          attemptBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder addAttempt(com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt value) {
        if (attemptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttemptIsMutable();
          attempt_.add(value);
          onChanged();
        } else {
          attemptBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder addAttempt(
          int index, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt value) {
        if (attemptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttemptIsMutable();
          attempt_.add(index, value);
          onChanged();
        } else {
          attemptBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder addAttempt(
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder builderForValue) {
        if (attemptBuilder_ == null) {
          ensureAttemptIsMutable();
          attempt_.add(builderForValue.build());
          onChanged();
        } else {
          attemptBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder addAttempt(
          int index, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder builderForValue) {
        if (attemptBuilder_ == null) {
          ensureAttemptIsMutable();
          attempt_.add(index, builderForValue.build());
          onChanged();
        } else {
          attemptBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder addAllAttempt(
          java.lang.Iterable<? extends com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt> values) {
        if (attemptBuilder_ == null) {
          ensureAttemptIsMutable();
          super.addAll(values, attempt_);
          onChanged();
        } else {
          attemptBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder clearAttempt() {
        if (attemptBuilder_ == null) {
          attempt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          attemptBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public Builder removeAttempt(int index) {
        if (attemptBuilder_ == null) {
          ensureAttemptIsMutable();
          attempt_.remove(index);
          onChanged();
        } else {
          attemptBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder getAttemptBuilder(
          int index) {
        return getAttemptFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder getAttemptOrBuilder(
          int index) {
        if (attemptBuilder_ == null) {
          return attempt_.get(index);  } else {
          return attemptBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public java.util.List<? extends com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder> 
           getAttemptOrBuilderList() {
        if (attemptBuilder_ != null) {
          return attemptBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attempt_);
        }
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder addAttemptBuilder() {
        return getAttemptFieldBuilder().addBuilder(
            com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance());
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder addAttemptBuilder(
          int index) {
        return getAttemptFieldBuilder().addBuilder(
            index, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.getDefaultInstance());
      }
      /**
       * <code>repeated .com.studio6.app.common.proto.WorkItem.Attempt attempt = 8;</code>
       */
      public java.util.List<com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder> 
           getAttemptBuilderList() {
        return getAttemptFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder, com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder> 
          getAttemptFieldBuilder() {
        if (attemptBuilder_ == null) {
          attemptBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt, com.studio6.app.common.proto.CommonProtos.WorkItem.Attempt.Builder, com.studio6.app.common.proto.CommonProtos.WorkItem.AttemptOrBuilder>(
                  attempt_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          attempt_ = null;
        }
        return attemptBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.studio6.app.common.proto.WorkItem)
    }

    static {
      defaultInstance = new WorkItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.studio6.app.common.proto.WorkItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_studio6_app_common_proto_WorkItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_studio6_app_common_proto_WorkItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_studio6_app_common_proto_WorkItem_Attempt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_studio6_app_common_proto_WorkItem_Attempt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\034com.studio6.app.common.p" +
      "roto\"\314\002\n\010WorkItem\022\n\n\002id\030\001 \002(\t\022\025\n\rcreatio" +
      "n_date\030\002 \002(\t\022\026\n\016max_process_ms\030\003 \002(\003\022\024\n\014" +
      "max_attempts\030\004 \002(\003\022 \n\030wait_between_attem" +
      "pts_ms\030\005 \002(\003\022\014\n\004item\030\006 \002(\014\022K\n\023in_progres" +
      "s_attempt\030\007 \001(\0132..com.studio6.app.common" +
      ".proto.WorkItem.Attempt\022?\n\007attempt\030\010 \003(\013" +
      "2..com.studio6.app.common.proto.WorkItem" +
      ".Attempt\0321\n\007Attempt\022\025\n\rcreation_date\030\001 \002" +
      "(\t\022\017\n\007message\030\002 \001(\tB,\n\034com.studio6.app.c",
      "ommon.protoB\014CommonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_studio6_app_common_proto_WorkItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_studio6_app_common_proto_WorkItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_studio6_app_common_proto_WorkItem_descriptor,
              new java.lang.String[] { "Id", "CreationDate", "MaxProcessMs", "MaxAttempts", "WaitBetweenAttemptsMs", "Item", "InProgressAttempt", "Attempt", });
          internal_static_com_studio6_app_common_proto_WorkItem_Attempt_descriptor =
            internal_static_com_studio6_app_common_proto_WorkItem_descriptor.getNestedTypes().get(0);
          internal_static_com_studio6_app_common_proto_WorkItem_Attempt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_studio6_app_common_proto_WorkItem_Attempt_descriptor,
              new java.lang.String[] { "CreationDate", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
