// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.studio6.app.common;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WorkQueueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.studio6.app.common.WorkQueue}
   */
  public static final class WorkQueue extends
      com.google.protobuf.GeneratedMessage
      implements WorkQueueOrBuilder {
    // Use WorkQueue.newBuilder() to construct.
    private WorkQueue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WorkQueue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WorkQueue defaultInstance;
    public static WorkQueue getDefaultInstance() {
      return defaultInstance;
    }

    public WorkQueue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WorkQueue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.studio6.app.common.CommonProtos.WorkQueue.class, com.studio6.app.common.CommonProtos.WorkQueue.Builder.class);
    }

    public static com.google.protobuf.Parser<WorkQueue> PARSER =
        new com.google.protobuf.AbstractParser<WorkQueue>() {
      public WorkQueue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkQueue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WorkQueue> getParserForType() {
      return PARSER;
    }

    public interface ItemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string id = 1;
      /**
       * <code>required string id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required string id = 1;</code>
       */
      java.lang.String getId();
      /**
       * <code>required string id = 1;</code>
       */
      com.google.protobuf.ByteString
          getIdBytes();

      // required string creation_date = 2;
      /**
       * <code>required string creation_date = 2;</code>
       */
      boolean hasCreationDate();
      /**
       * <code>required string creation_date = 2;</code>
       */
      java.lang.String getCreationDate();
      /**
       * <code>required string creation_date = 2;</code>
       */
      com.google.protobuf.ByteString
          getCreationDateBytes();

      // required int64 max_process_ms = 3;
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      boolean hasMaxProcessMs();
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      long getMaxProcessMs();

      // required bytes item = 4;
      /**
       * <code>required bytes item = 4;</code>
       */
      boolean hasItem();
      /**
       * <code>required bytes item = 4;</code>
       */
      com.google.protobuf.ByteString getItem();

      // optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;
      /**
       * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
       */
      boolean hasInProgressAttempt();
      /**
       * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
       */
      com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt getInProgressAttempt();
      /**
       * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
       */
      com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder getInProgressAttemptOrBuilder();

      // repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      java.util.List<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt> 
          getAttemptsList();
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt getAttempts(int index);
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      int getAttemptsCount();
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      java.util.List<? extends com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder> 
          getAttemptsOrBuilderList();
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder getAttemptsOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code com.studio6.app.common.WorkQueue.Item}
     */
    public static final class Item extends
        com.google.protobuf.GeneratedMessage
        implements ItemOrBuilder {
      // Use Item.newBuilder() to construct.
      private Item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Item defaultInstance;
      public static Item getDefaultInstance() {
        return defaultInstance;
      }

      public Item getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Item(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                id_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                creationDate_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                maxProcessMs_ = input.readInt64();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                item_ = input.readBytes();
                break;
              }
              case 42: {
                com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder subBuilder = null;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                  subBuilder = inProgressAttempt_.toBuilder();
                }
                inProgressAttempt_ = input.readMessage(com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(inProgressAttempt_);
                  inProgressAttempt_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000010;
                break;
              }
              case 50: {
                if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                  attempts_ = new java.util.ArrayList<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt>();
                  mutable_bitField0_ |= 0x00000020;
                }
                attempts_.add(input.readMessage(com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
            attempts_ = java.util.Collections.unmodifiableList(attempts_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.studio6.app.common.CommonProtos.WorkQueue.Item.class, com.studio6.app.common.CommonProtos.WorkQueue.Item.Builder.class);
      }

      public static com.google.protobuf.Parser<Item> PARSER =
          new com.google.protobuf.AbstractParser<Item>() {
        public Item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Item> getParserForType() {
        return PARSER;
      }

      public interface AttemptOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

        // required string creation_date = 1;
        /**
         * <code>required string creation_date = 1;</code>
         */
        boolean hasCreationDate();
        /**
         * <code>required string creation_date = 1;</code>
         */
        java.lang.String getCreationDate();
        /**
         * <code>required string creation_date = 1;</code>
         */
        com.google.protobuf.ByteString
            getCreationDateBytes();

        // optional string message = 2;
        /**
         * <code>optional string message = 2;</code>
         */
        boolean hasMessage();
        /**
         * <code>optional string message = 2;</code>
         */
        java.lang.String getMessage();
        /**
         * <code>optional string message = 2;</code>
         */
        com.google.protobuf.ByteString
            getMessageBytes();
      }
      /**
       * Protobuf type {@code com.studio6.app.common.WorkQueue.Item.Attempt}
       */
      public static final class Attempt extends
          com.google.protobuf.GeneratedMessage
          implements AttemptOrBuilder {
        // Use Attempt.newBuilder() to construct.
        private Attempt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
          super(builder);
          this.unknownFields = builder.getUnknownFields();
        }
        private Attempt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final Attempt defaultInstance;
        public static Attempt getDefaultInstance() {
          return defaultInstance;
        }

        public Attempt getDefaultInstanceForType() {
          return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
          return this.unknownFields;
        }
        private Attempt(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          initFields();
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  creationDate_ = input.readBytes();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  message_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.class, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder.class);
        }

        public static com.google.protobuf.Parser<Attempt> PARSER =
            new com.google.protobuf.AbstractParser<Attempt>() {
          public Attempt parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Attempt(input, extensionRegistry);
          }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<Attempt> getParserForType() {
          return PARSER;
        }

        private int bitField0_;
        // required string creation_date = 1;
        public static final int CREATION_DATE_FIELD_NUMBER = 1;
        private java.lang.Object creationDate_;
        /**
         * <code>required string creation_date = 1;</code>
         */
        public boolean hasCreationDate() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string creation_date = 1;</code>
         */
        public java.lang.String getCreationDate() {
          java.lang.Object ref = creationDate_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              creationDate_ = s;
            }
            return s;
          }
        }
        /**
         * <code>required string creation_date = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCreationDateBytes() {
          java.lang.Object ref = creationDate_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            creationDate_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        // optional string message = 2;
        public static final int MESSAGE_FIELD_NUMBER = 2;
        private java.lang.Object message_;
        /**
         * <code>optional string message = 2;</code>
         */
        public boolean hasMessage() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public java.lang.String getMessage() {
          java.lang.Object ref = message_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              message_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMessageBytes() {
          java.lang.Object ref = message_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            message_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private void initFields() {
          creationDate_ = "";
          message_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;

          if (!hasCreationDate()) {
            memoizedIsInitialized = 0;
            return false;
          }
          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBytes(1, getCreationDateBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeBytes(2, getMessageBytes());
          }
          getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, getCreationDateBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(2, getMessageBytes());
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }

        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code com.studio6.app.common.WorkQueue.Item.Attempt}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_descriptor;
          }

          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.class, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder.class);
          }

          // Construct using com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }

          public Builder clear() {
            super.clear();
            creationDate_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            message_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }

          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }

          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_descriptor;
          }

          public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt getDefaultInstanceForType() {
            return com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance();
          }

          public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt build() {
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt buildPartial() {
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt result = new com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.creationDate_ = creationDate_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.message_ = message_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }

          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt) {
              return mergeFrom((com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt other) {
            if (other == com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance()) return this;
            if (other.hasCreationDate()) {
              bitField0_ |= 0x00000001;
              creationDate_ = other.creationDate_;
              onChanged();
            }
            if (other.hasMessage()) {
              bitField0_ |= 0x00000002;
              message_ = other.message_;
              onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }

          public final boolean isInitialized() {
            if (!hasCreationDate()) {
              
              return false;
            }
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt) e.getUnfinishedMessage();
              throw e;
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          // required string creation_date = 1;
          private java.lang.Object creationDate_ = "";
          /**
           * <code>required string creation_date = 1;</code>
           */
          public boolean hasCreationDate() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          /**
           * <code>required string creation_date = 1;</code>
           */
          public java.lang.String getCreationDate() {
            java.lang.Object ref = creationDate_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              creationDate_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>required string creation_date = 1;</code>
           */
          public com.google.protobuf.ByteString
              getCreationDateBytes() {
            java.lang.Object ref = creationDate_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              creationDate_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>required string creation_date = 1;</code>
           */
          public Builder setCreationDate(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            creationDate_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>required string creation_date = 1;</code>
           */
          public Builder clearCreationDate() {
            bitField0_ = (bitField0_ & ~0x00000001);
            creationDate_ = getDefaultInstance().getCreationDate();
            onChanged();
            return this;
          }
          /**
           * <code>required string creation_date = 1;</code>
           */
          public Builder setCreationDateBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            creationDate_ = value;
            onChanged();
            return this;
          }

          // optional string message = 2;
          private java.lang.Object message_ = "";
          /**
           * <code>optional string message = 2;</code>
           */
          public boolean hasMessage() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          /**
           * <code>optional string message = 2;</code>
           */
          public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              message_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string message = 2;</code>
           */
          public com.google.protobuf.ByteString
              getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              message_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string message = 2;</code>
           */
          public Builder setMessage(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            message_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string message = 2;</code>
           */
          public Builder clearMessage() {
            bitField0_ = (bitField0_ & ~0x00000002);
            message_ = getDefaultInstance().getMessage();
            onChanged();
            return this;
          }
          /**
           * <code>optional string message = 2;</code>
           */
          public Builder setMessageBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            message_ = value;
            onChanged();
            return this;
          }

          // @@protoc_insertion_point(builder_scope:com.studio6.app.common.WorkQueue.Item.Attempt)
        }

        static {
          defaultInstance = new Attempt(true);
          defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.studio6.app.common.WorkQueue.Item.Attempt)
      }

      private int bitField0_;
      // required string id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private java.lang.Object id_;
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string creation_date = 2;
      public static final int CREATION_DATE_FIELD_NUMBER = 2;
      private java.lang.Object creationDate_;
      /**
       * <code>required string creation_date = 2;</code>
       */
      public boolean hasCreationDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string creation_date = 2;</code>
       */
      public java.lang.String getCreationDate() {
        java.lang.Object ref = creationDate_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            creationDate_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string creation_date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCreationDateBytes() {
        java.lang.Object ref = creationDate_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creationDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required int64 max_process_ms = 3;
      public static final int MAX_PROCESS_MS_FIELD_NUMBER = 3;
      private long maxProcessMs_;
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      public boolean hasMaxProcessMs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 max_process_ms = 3;</code>
       */
      public long getMaxProcessMs() {
        return maxProcessMs_;
      }

      // required bytes item = 4;
      public static final int ITEM_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString item_;
      /**
       * <code>required bytes item = 4;</code>
       */
      public boolean hasItem() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes item = 4;</code>
       */
      public com.google.protobuf.ByteString getItem() {
        return item_;
      }

      // optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;
      public static final int IN_PROGRESS_ATTEMPT_FIELD_NUMBER = 5;
      private com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt inProgressAttempt_;
      /**
       * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
       */
      public boolean hasInProgressAttempt() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
       */
      public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt getInProgressAttempt() {
        return inProgressAttempt_;
      }
      /**
       * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
       */
      public com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder getInProgressAttemptOrBuilder() {
        return inProgressAttempt_;
      }

      // repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;
      public static final int ATTEMPTS_FIELD_NUMBER = 6;
      private java.util.List<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt> attempts_;
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      public java.util.List<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt> getAttemptsList() {
        return attempts_;
      }
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      public java.util.List<? extends com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder> 
          getAttemptsOrBuilderList() {
        return attempts_;
      }
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      public int getAttemptsCount() {
        return attempts_.size();
      }
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt getAttempts(int index) {
        return attempts_.get(index);
      }
      /**
       * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
       */
      public com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder getAttemptsOrBuilder(
          int index) {
        return attempts_.get(index);
      }

      private void initFields() {
        id_ = "";
        creationDate_ = "";
        maxProcessMs_ = 0L;
        item_ = com.google.protobuf.ByteString.EMPTY;
        inProgressAttempt_ = com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance();
        attempts_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCreationDate()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMaxProcessMs()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasItem()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (hasInProgressAttempt()) {
          if (!getInProgressAttempt().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        for (int i = 0; i < getAttemptsCount(); i++) {
          if (!getAttempts(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getCreationDateBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(3, maxProcessMs_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, item_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeMessage(5, inProgressAttempt_);
        }
        for (int i = 0; i < attempts_.size(); i++) {
          output.writeMessage(6, attempts_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCreationDateBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, maxProcessMs_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, item_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, inProgressAttempt_);
        }
        for (int i = 0; i < attempts_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, attempts_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.studio6.app.common.CommonProtos.WorkQueue.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.studio6.app.common.CommonProtos.WorkQueue.Item prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.studio6.app.common.WorkQueue.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.studio6.app.common.CommonProtos.WorkQueue.ItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.studio6.app.common.CommonProtos.WorkQueue.Item.class, com.studio6.app.common.CommonProtos.WorkQueue.Item.Builder.class);
        }

        // Construct using com.studio6.app.common.CommonProtos.WorkQueue.Item.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getInProgressAttemptFieldBuilder();
            getAttemptsFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          creationDate_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          maxProcessMs_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          item_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          if (inProgressAttemptBuilder_ == null) {
            inProgressAttempt_ = com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance();
          } else {
            inProgressAttemptBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000010);
          if (attemptsBuilder_ == null) {
            attempts_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            attemptsBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_Item_descriptor;
        }

        public com.studio6.app.common.CommonProtos.WorkQueue.Item getDefaultInstanceForType() {
          return com.studio6.app.common.CommonProtos.WorkQueue.Item.getDefaultInstance();
        }

        public com.studio6.app.common.CommonProtos.WorkQueue.Item build() {
          com.studio6.app.common.CommonProtos.WorkQueue.Item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.studio6.app.common.CommonProtos.WorkQueue.Item buildPartial() {
          com.studio6.app.common.CommonProtos.WorkQueue.Item result = new com.studio6.app.common.CommonProtos.WorkQueue.Item(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.creationDate_ = creationDate_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.maxProcessMs_ = maxProcessMs_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.item_ = item_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          if (inProgressAttemptBuilder_ == null) {
            result.inProgressAttempt_ = inProgressAttempt_;
          } else {
            result.inProgressAttempt_ = inProgressAttemptBuilder_.build();
          }
          if (attemptsBuilder_ == null) {
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
              attempts_ = java.util.Collections.unmodifiableList(attempts_);
              bitField0_ = (bitField0_ & ~0x00000020);
            }
            result.attempts_ = attempts_;
          } else {
            result.attempts_ = attemptsBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.studio6.app.common.CommonProtos.WorkQueue.Item) {
            return mergeFrom((com.studio6.app.common.CommonProtos.WorkQueue.Item)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.studio6.app.common.CommonProtos.WorkQueue.Item other) {
          if (other == com.studio6.app.common.CommonProtos.WorkQueue.Item.getDefaultInstance()) return this;
          if (other.hasId()) {
            bitField0_ |= 0x00000001;
            id_ = other.id_;
            onChanged();
          }
          if (other.hasCreationDate()) {
            bitField0_ |= 0x00000002;
            creationDate_ = other.creationDate_;
            onChanged();
          }
          if (other.hasMaxProcessMs()) {
            setMaxProcessMs(other.getMaxProcessMs());
          }
          if (other.hasItem()) {
            setItem(other.getItem());
          }
          if (other.hasInProgressAttempt()) {
            mergeInProgressAttempt(other.getInProgressAttempt());
          }
          if (attemptsBuilder_ == null) {
            if (!other.attempts_.isEmpty()) {
              if (attempts_.isEmpty()) {
                attempts_ = other.attempts_;
                bitField0_ = (bitField0_ & ~0x00000020);
              } else {
                ensureAttemptsIsMutable();
                attempts_.addAll(other.attempts_);
              }
              onChanged();
            }
          } else {
            if (!other.attempts_.isEmpty()) {
              if (attemptsBuilder_.isEmpty()) {
                attemptsBuilder_.dispose();
                attemptsBuilder_ = null;
                attempts_ = other.attempts_;
                bitField0_ = (bitField0_ & ~0x00000020);
                attemptsBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getAttemptsFieldBuilder() : null;
              } else {
                attemptsBuilder_.addAllMessages(other.attempts_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasCreationDate()) {
            
            return false;
          }
          if (!hasMaxProcessMs()) {
            
            return false;
          }
          if (!hasItem()) {
            
            return false;
          }
          if (hasInProgressAttempt()) {
            if (!getInProgressAttempt().isInitialized()) {
              
              return false;
            }
          }
          for (int i = 0; i < getAttemptsCount(); i++) {
            if (!getAttempts(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.studio6.app.common.CommonProtos.WorkQueue.Item parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.studio6.app.common.CommonProtos.WorkQueue.Item) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string id = 1;
        private java.lang.Object id_ = "";
        /**
         * <code>required string id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string id = 1;</code>
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }

        // required string creation_date = 2;
        private java.lang.Object creationDate_ = "";
        /**
         * <code>required string creation_date = 2;</code>
         */
        public boolean hasCreationDate() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string creation_date = 2;</code>
         */
        public java.lang.String getCreationDate() {
          java.lang.Object ref = creationDate_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            creationDate_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string creation_date = 2;</code>
         */
        public com.google.protobuf.ByteString
            getCreationDateBytes() {
          java.lang.Object ref = creationDate_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            creationDate_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string creation_date = 2;</code>
         */
        public Builder setCreationDate(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          creationDate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string creation_date = 2;</code>
         */
        public Builder clearCreationDate() {
          bitField0_ = (bitField0_ & ~0x00000002);
          creationDate_ = getDefaultInstance().getCreationDate();
          onChanged();
          return this;
        }
        /**
         * <code>required string creation_date = 2;</code>
         */
        public Builder setCreationDateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          creationDate_ = value;
          onChanged();
          return this;
        }

        // required int64 max_process_ms = 3;
        private long maxProcessMs_ ;
        /**
         * <code>required int64 max_process_ms = 3;</code>
         */
        public boolean hasMaxProcessMs() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int64 max_process_ms = 3;</code>
         */
        public long getMaxProcessMs() {
          return maxProcessMs_;
        }
        /**
         * <code>required int64 max_process_ms = 3;</code>
         */
        public Builder setMaxProcessMs(long value) {
          bitField0_ |= 0x00000004;
          maxProcessMs_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 max_process_ms = 3;</code>
         */
        public Builder clearMaxProcessMs() {
          bitField0_ = (bitField0_ & ~0x00000004);
          maxProcessMs_ = 0L;
          onChanged();
          return this;
        }

        // required bytes item = 4;
        private com.google.protobuf.ByteString item_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes item = 4;</code>
         */
        public boolean hasItem() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required bytes item = 4;</code>
         */
        public com.google.protobuf.ByteString getItem() {
          return item_;
        }
        /**
         * <code>required bytes item = 4;</code>
         */
        public Builder setItem(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          item_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes item = 4;</code>
         */
        public Builder clearItem() {
          bitField0_ = (bitField0_ & ~0x00000008);
          item_ = getDefaultInstance().getItem();
          onChanged();
          return this;
        }

        // optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;
        private com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt inProgressAttempt_ = com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder, com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder> inProgressAttemptBuilder_;
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public boolean hasInProgressAttempt() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt getInProgressAttempt() {
          if (inProgressAttemptBuilder_ == null) {
            return inProgressAttempt_;
          } else {
            return inProgressAttemptBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public Builder setInProgressAttempt(com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt value) {
          if (inProgressAttemptBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            inProgressAttempt_ = value;
            onChanged();
          } else {
            inProgressAttemptBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public Builder setInProgressAttempt(
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder builderForValue) {
          if (inProgressAttemptBuilder_ == null) {
            inProgressAttempt_ = builderForValue.build();
            onChanged();
          } else {
            inProgressAttemptBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public Builder mergeInProgressAttempt(com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt value) {
          if (inProgressAttemptBuilder_ == null) {
            if (((bitField0_ & 0x00000010) == 0x00000010) &&
                inProgressAttempt_ != com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance()) {
              inProgressAttempt_ =
                com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.newBuilder(inProgressAttempt_).mergeFrom(value).buildPartial();
            } else {
              inProgressAttempt_ = value;
            }
            onChanged();
          } else {
            inProgressAttemptBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public Builder clearInProgressAttempt() {
          if (inProgressAttemptBuilder_ == null) {
            inProgressAttempt_ = com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance();
            onChanged();
          } else {
            inProgressAttemptBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder getInProgressAttemptBuilder() {
          bitField0_ |= 0x00000010;
          onChanged();
          return getInProgressAttemptFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder getInProgressAttemptOrBuilder() {
          if (inProgressAttemptBuilder_ != null) {
            return inProgressAttemptBuilder_.getMessageOrBuilder();
          } else {
            return inProgressAttempt_;
          }
        }
        /**
         * <code>optional .com.studio6.app.common.WorkQueue.Item.Attempt in_progress_attempt = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder, com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder> 
            getInProgressAttemptFieldBuilder() {
          if (inProgressAttemptBuilder_ == null) {
            inProgressAttemptBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder, com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder>(
                    inProgressAttempt_,
                    getParentForChildren(),
                    isClean());
            inProgressAttempt_ = null;
          }
          return inProgressAttemptBuilder_;
        }

        // repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;
        private java.util.List<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt> attempts_ =
          java.util.Collections.emptyList();
        private void ensureAttemptsIsMutable() {
          if (!((bitField0_ & 0x00000020) == 0x00000020)) {
            attempts_ = new java.util.ArrayList<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt>(attempts_);
            bitField0_ |= 0x00000020;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder, com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder> attemptsBuilder_;

        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public java.util.List<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt> getAttemptsList() {
          if (attemptsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(attempts_);
          } else {
            return attemptsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public int getAttemptsCount() {
          if (attemptsBuilder_ == null) {
            return attempts_.size();
          } else {
            return attemptsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt getAttempts(int index) {
          if (attemptsBuilder_ == null) {
            return attempts_.get(index);
          } else {
            return attemptsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder setAttempts(
            int index, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt value) {
          if (attemptsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureAttemptsIsMutable();
            attempts_.set(index, value);
            onChanged();
          } else {
            attemptsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder setAttempts(
            int index, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder builderForValue) {
          if (attemptsBuilder_ == null) {
            ensureAttemptsIsMutable();
            attempts_.set(index, builderForValue.build());
            onChanged();
          } else {
            attemptsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder addAttempts(com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt value) {
          if (attemptsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureAttemptsIsMutable();
            attempts_.add(value);
            onChanged();
          } else {
            attemptsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder addAttempts(
            int index, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt value) {
          if (attemptsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureAttemptsIsMutable();
            attempts_.add(index, value);
            onChanged();
          } else {
            attemptsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder addAttempts(
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder builderForValue) {
          if (attemptsBuilder_ == null) {
            ensureAttemptsIsMutable();
            attempts_.add(builderForValue.build());
            onChanged();
          } else {
            attemptsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder addAttempts(
            int index, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder builderForValue) {
          if (attemptsBuilder_ == null) {
            ensureAttemptsIsMutable();
            attempts_.add(index, builderForValue.build());
            onChanged();
          } else {
            attemptsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder addAllAttempts(
            java.lang.Iterable<? extends com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt> values) {
          if (attemptsBuilder_ == null) {
            ensureAttemptsIsMutable();
            super.addAll(values, attempts_);
            onChanged();
          } else {
            attemptsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder clearAttempts() {
          if (attemptsBuilder_ == null) {
            attempts_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000020);
            onChanged();
          } else {
            attemptsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public Builder removeAttempts(int index) {
          if (attemptsBuilder_ == null) {
            ensureAttemptsIsMutable();
            attempts_.remove(index);
            onChanged();
          } else {
            attemptsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder getAttemptsBuilder(
            int index) {
          return getAttemptsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder getAttemptsOrBuilder(
            int index) {
          if (attemptsBuilder_ == null) {
            return attempts_.get(index);  } else {
            return attemptsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public java.util.List<? extends com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder> 
             getAttemptsOrBuilderList() {
          if (attemptsBuilder_ != null) {
            return attemptsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(attempts_);
          }
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder addAttemptsBuilder() {
          return getAttemptsFieldBuilder().addBuilder(
              com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance());
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder addAttemptsBuilder(
            int index) {
          return getAttemptsFieldBuilder().addBuilder(
              index, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.getDefaultInstance());
        }
        /**
         * <code>repeated .com.studio6.app.common.WorkQueue.Item.Attempt attempts = 6;</code>
         */
        public java.util.List<com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder> 
             getAttemptsBuilderList() {
          return getAttemptsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder, com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder> 
            getAttemptsFieldBuilder() {
          if (attemptsBuilder_ == null) {
            attemptsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt, com.studio6.app.common.CommonProtos.WorkQueue.Item.Attempt.Builder, com.studio6.app.common.CommonProtos.WorkQueue.Item.AttemptOrBuilder>(
                    attempts_,
                    ((bitField0_ & 0x00000020) == 0x00000020),
                    getParentForChildren(),
                    isClean());
            attempts_ = null;
          }
          return attemptsBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:com.studio6.app.common.WorkQueue.Item)
      }

      static {
        defaultInstance = new Item(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.studio6.app.common.WorkQueue.Item)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.studio6.app.common.CommonProtos.WorkQueue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.studio6.app.common.CommonProtos.WorkQueue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.studio6.app.common.WorkQueue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.studio6.app.common.CommonProtos.WorkQueueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.studio6.app.common.CommonProtos.WorkQueue.class, com.studio6.app.common.CommonProtos.WorkQueue.Builder.class);
      }

      // Construct using com.studio6.app.common.CommonProtos.WorkQueue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.studio6.app.common.CommonProtos.internal_static_com_studio6_app_common_WorkQueue_descriptor;
      }

      public com.studio6.app.common.CommonProtos.WorkQueue getDefaultInstanceForType() {
        return com.studio6.app.common.CommonProtos.WorkQueue.getDefaultInstance();
      }

      public com.studio6.app.common.CommonProtos.WorkQueue build() {
        com.studio6.app.common.CommonProtos.WorkQueue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.studio6.app.common.CommonProtos.WorkQueue buildPartial() {
        com.studio6.app.common.CommonProtos.WorkQueue result = new com.studio6.app.common.CommonProtos.WorkQueue(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.studio6.app.common.CommonProtos.WorkQueue) {
          return mergeFrom((com.studio6.app.common.CommonProtos.WorkQueue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.studio6.app.common.CommonProtos.WorkQueue other) {
        if (other == com.studio6.app.common.CommonProtos.WorkQueue.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.studio6.app.common.CommonProtos.WorkQueue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.studio6.app.common.CommonProtos.WorkQueue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.studio6.app.common.WorkQueue)
    }

    static {
      defaultInstance = new WorkQueue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.studio6.app.common.WorkQueue)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_studio6_app_common_WorkQueue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_studio6_app_common_WorkQueue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_studio6_app_common_WorkQueue_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_studio6_app_common_WorkQueue_Item_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\026com.studio6.app.common\"\237" +
      "\002\n\tWorkQueue\032\221\002\n\004Item\022\n\n\002id\030\001 \002(\t\022\025\n\rcre" +
      "ation_date\030\002 \002(\t\022\026\n\016max_process_ms\030\003 \002(\003" +
      "\022\014\n\004item\030\004 \002(\014\022K\n\023in_progress_attempt\030\005 " +
      "\001(\0132..com.studio6.app.common.WorkQueue.I" +
      "tem.Attempt\022@\n\010attempts\030\006 \003(\0132..com.stud" +
      "io6.app.common.WorkQueue.Item.Attempt\0321\n" +
      "\007Attempt\022\025\n\rcreation_date\030\001 \002(\t\022\017\n\007messa" +
      "ge\030\002 \001(\tB&\n\026com.studio6.app.commonB\014Comm" +
      "onProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_studio6_app_common_WorkQueue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_studio6_app_common_WorkQueue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_studio6_app_common_WorkQueue_descriptor,
              new java.lang.String[] { });
          internal_static_com_studio6_app_common_WorkQueue_Item_descriptor =
            internal_static_com_studio6_app_common_WorkQueue_descriptor.getNestedTypes().get(0);
          internal_static_com_studio6_app_common_WorkQueue_Item_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_studio6_app_common_WorkQueue_Item_descriptor,
              new java.lang.String[] { "Id", "CreationDate", "MaxProcessMs", "Item", "InProgressAttempt", "Attempts", });
          internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_descriptor =
            internal_static_com_studio6_app_common_WorkQueue_Item_descriptor.getNestedTypes().get(0);
          internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_studio6_app_common_WorkQueue_Item_Attempt_descriptor,
              new java.lang.String[] { "CreationDate", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
